<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="description" content="I'm a student and developer studying Electrical Engineering with a minor in Computer Engineering at the University of Calgary.">
    <meta property='og:image' content="/img/meta/meta.png" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://salahsheikh.me" />
    <meta name="keyword" content="Salah, Sheikh, University, Calgary, Portfolio, Computer engineering, electrical engineering, website, Synopsys, AMD, Developer, Engineer, Software, 2021, intern">
    <title>PAGE_TITLE</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <link rel="stylesheet" href="./css/main.min.css">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156816686-1"></script>
    <script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'UA-156816686-1');</script>
</head>
#undef PAGE_TITLE
